services:
  - type: web
    name: student-performance-app
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn application:app
    envVars:
      - key: PORT
        value: 10000